### ISSUE TITLE
开发模式切换页面时会出错，刷新后恢复

### ISSUE THREAD

**Issue by glkwhr** [TRPGEngine/Client#173]
输入注册过的账号点击“登陆"后就转到错误页面。
![image](https://user-images.githubusercontent.com/4232536/120262161-2e013200-c24e-11eb-80db-45b59d4f7008.png)

刷新一次或几次后可以进入 http://127.0.0.1:8089/main/personal/friends 界面。之后可以进行正常创建团，上传头像等操作。但每次切换页面是都会转到错误页面（比如在`/main/group/7a60b0f0-c288-11eb-bd53-97166aeb258f/lobby` 和 `/main/personal/friends`之间切换。错误信息示例如下：
![image](https://user-images.githubusercontent.com/4232536/120261610-170e1000-c24d-11eb-90df-6c846ace4c12.png)

后台收到的错误报告示例如下：
```
trpg:webservice:koa <-- OPTIONS /report/error +3s
  trpg:webservice:koa --> OPTIONS /report/error 204 1ms  +1ms
  trpg:webservice:koa <-- POST /report/error +2ms
report err from ::ffff:127.0.0.1 stack 
    at Lifecycle (webpack-internal:///./node_modules/react-router/esm/react-router.js:203:29)
    at Redirect (webpack-internal:///./node_modules/react-router/esm/react-router.js:304:28)
    at Switch (webpack-internal:///./node_modules/react-router/esm/react-router.js:649:29)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:782:6)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:782:6)
    at eval (webpack-internal:///./src/web/routes/Main/Content/PageContent.tsx:77:90)
    at eval (webpack-internal:///./src/web/routes/Main/Content/PageContent.tsx:99:23)
    at eval (webpack-internal:///./src/web/routes/Main/Content/Group/GroupProvider.tsx:20:25)
    at eval (webpack-internal:///./src/web/routes/Main/Content/Group/index.tsx:38:72)
    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:447:29)
    at Switch (webpack-internal:///./node_modules/react-router/esm/react-router.js:649:29)
    at MainContent
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:782:6)
    at div
    at O (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:782:6)
    at eval (webpack-internal:///./src/web/routes/Main/SidebarContext.tsx:50:66)
    at MainRoute
    at Route (webpack-internal:///./node_modules/react-router/esm/react-router.js:447:29)
    at Switch (webpack-internal:///./node_modules/react-router/esm/react-router.js:649:29)
    at eval (webpack-internal:///./src/shared/components/portal/buildPortal.tsx:41:67)
    at eval (webpack-internal:///./src/web/components/portal/PortalProvider.tsx:16:67)
    at eval (webpack-internal:///./src/web/components/rtc/GlobalVoice.tsx:33:211)
    at Provider (webpack-internal:///./node_modules/react-redux/es/components/Provider.js:15:20)
    at eval (webpack-internal:///./src/rtc/redux/index.tsx:98:12)
    at eval (webpack-internal:///./src/rtc/RoomContext.tsx:226:66)
    at eval (webpack-internal:///./src/web/components/PWAContext.tsx:55:66)
    at CustomProvider (webpack-internal:///./src/web/routes/App.tsx:53:74)
    at div
    at ErrorBoundary (webpack-internal:///./src/web/containers/ErrorBoundary.tsx:47:43)
    at Router (webpack-internal:///./node_modules/react-router/esm/react-router.js:82:30)
    at BrowserRouter (webpack-internal:///./node_modules/react-router-dom/esm/react-router-dom.js:56:35)
    at App
    at InnerLoadable (webpack-internal:///./node_modules/@loadable/component/dist/loadable.esm.js:162:34)
    at LoadableWithChunkExtractor
    at Loadable
    at FormProvider (webpack-internal:///./node_modules/rc-field-form/es/FormContext.js:19:31)
    at LocaleProvider (webpack-internal:///./node_modules/antd/es/locale-provider/index.js:34:87)
    at ProviderChildren (webpack-internal:///./node_modules/antd/es/config-provider/index.js:77:24)
    at LocaleReceiver (webpack-internal:///./node_modules/antd/es/locale-provider/LocaleReceiver.js:29:87)
    at ConfigProvider (webpack-internal:///./node_modules/antd/es/config-provider/index.js:185:13)
    at Ge (webpack-internal:///./node_modules/styled-components/dist/styled-components.browser.esm.js:689:60)
    at eval (webpack-internal:///./src/shared/context/ThemeContext.tsx:51:66)
    at Provider (webpack-internal:///./node_modules/react-redux/es/components/Provider.js:15:20)
  trpg:storage:sql Executing (default): INSERT INTO `report_error` (`id`,`ip`,`ua`,`version`,`message`,`stack`,`createdAt`,`updatedAt`) VALUES (DEFAULT,?,?,?,?,?,?,?); +147ms
  trpg:webservice:koa --> POST /report/error 200 152ms 12b +5ms
```

**Comment by moonrailgun** [comment]
执行一次`yarn run plugins:all`

**Comment by glkwhr** [comment]
多谢修复，已解决
